version: '3'
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"

  sender:
    build: ./sender
    container_name: sender
    depends_on:
      - server

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
